### ISSUE TITLE
模板的插图索引章节之间有空行，这个怎么设置它没有呢

### ISSUE THREAD

**Issue by liurongfang** [103yiran/XDUthesis_xelatex#2]
如图所示
![Annotation 2019-05-10 160216](https://user-images.githubusercontent.com/18704341/57512100-594e1700-733d-11e9-9179-6aa14fa1e743.png)
第一章的插图索引和第二章的插图索引之间空了一行，论文评审时被指出了这个问题，请问这个应该怎么设置不空行呢？谢谢！

**Comment by 103yiran** [comment]
相隔太久，可以在论坛问一下吗？

**Comment by liurongfang** [comment]
> 相隔太久，可以在论坛问一下吗？

好的，谢谢你
